# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dove & The Seagull
email: m@kevan.tv
description: High quality retro & vintage inspired art poster prints
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://www.thedoveandtheseagull.com" # the base hostname & protocol for your sites

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

cloudinary_url: https://res.cloudinary.com/dl4abuxel/image/upload
thumbnail: c_scale,w_400
a4_frame_large: c_scale,q_auto,w_800/c_mpad,g_center,h_1212,w_880/g_center,l_A_frame
a4_frame_small: c_scale,q_auto,w_800/c_mpad,g_center,h_1212,w_880/g_center,l_A_frame/c_scale,w_400
8x10_frame_large: c_scale,q_auto,w_800/c_mpad,g_center,h_1080,w_880/g_center,l_8x10_frame
8x10_frame_small: c_scale,q_auto,w_800/c_mpad,g_center,h_1080,w_880/g_center,l_8x10_frame/c_scale,w_400
thumbnail_square: c_scale,w_400/c_crop,g_face:center,h_400,w_400
excerpt_separator: ---
collections:
  categories:
    output: true
    permalink: /categories/:path/
  collect:
    output: true
    permalink: /collections/:path/
  artwork:
    output: true
    permalink: /artwork/:path/
  artist:
    output: true
    permalink: /artists/:path/

defaults:
  -
    scope:
      path: ""
      type: categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: collect
    values:
      layout: collection
  -
    scope:
      path: ""
      type: artwork
    values:
      layout: artwork
  -
    scope:
      path: ""
      type: artist
    values:
      layout: artist