# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dove & The Seagull
email: m@kevan.tv
description: High quality art prints
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


gems:
  - jekyll-sitemap


# Build settings
markdown: kramdown

collections:
  product:
    output: true
    permalink: /shop/:path/

defaults:
  -
    scope:
      path: ""
      type: "product"
    values:
      layout: "product"
