# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dove & The Seagull
email: m@kevan.tv
description: High quality retro & vintage inspired art poster prints
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thedoveandtheseagull.com" # the base hostname & protocol for your site

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
    
# Build settings
markdown: kramdown

collections:
  section:
    output: true
    permalink: /shop/:path/
  collection:
    output: true
    permalink: /collections/:path/

defaults:
  -
    scope:
      path: ""
      type: section
    values:
      layout: page
  -
    scope:
      path: ""
      type: collection
    values:
      layout: page
